# Generated by Django 3.1.4 on 2020-12-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('horsePower', models.CharField(max_length=50)),
                ('transStyle', models.CharField(max_length=50)),
                ('engineStyle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('productImage', models.ImageField(default='default.png', upload_to='motorcycle_images')),
            ],
        ),
    ]
