# Generated by Django 3.1.4 on 2020-12-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='engineCapacity',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='horsePower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
