# Generated by Django 3.1.4 on 2020-12-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201208_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='model',
            field=models.CharField(default='Model', max_length=100),
        ),
    ]
