# Generated by Django 3.1.4 on 2020-12-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201209_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='productImage',
            field=models.ImageField(default='default.jpg', upload_to='motorcycle_images'),
        ),
    ]
