# Generated by Django 3.1.4 on 2020-12-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_motorcycle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
