# Generated by Django 3.1.4 on 2020-12-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
