# Generated by Django 3.1.4 on 2020-12-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20201211_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='likes',
            field=models.TextField(default=''),
        ),
    ]
