# Generated by Django 3.1.4 on 2020-12-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20201211_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
